name: Update Blog Page

on:
  push:
    paths:
      - 'blogs/**' # This watches for changes in the 'blogs' folder

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Python and Run Script
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'  # Replace 'x' with the desired Python version
        run: |
          python3 \script.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "jaypalla23@gmail.com"
          git config --local user.name "JayanthPalla"
          git add .
          git commit -m "Update blog links"
          git push
